"""
Document type definitions: field schemas and AI guidance for all supported types.
"""
from typing import Any

# Catalog key → document config
DOC_TYPES: dict[str, dict[str, Any]] = {
    "Mutual-NDA": {
        "name": "Mutual Non-Disclosure Agreement",
        "description": "Common Paper standard Mutual Non-Disclosure Agreement",
        "filename": "Mutual-NDA.md",
        "default_values": {
            "purpose": "Evaluating whether to enter into a business relationship with the other party.",
            "effectiveDate": "",
            "mndaTermType": "fixed",
            "mndaTermYears": "1",
            "confidentialityTermType": "fixed",
            "confidentialityTermYears": "1",
            "governingLaw": "",
            "jurisdiction": "",
            "party1Name": "",
            "party1Title": "",
            "party1Company": "",
            "party1Address": "",
            "party2Name": "",
            "party2Title": "",
            "party2Company": "",
            "party2Address": "",
        },
        "questions_order": [
            "Party 1: name and company (one question)",
            "Party 1: job title and mailing address (one question)",
            "Party 2: name and company (one question)",
            "Party 2: job title and mailing address (one question)",
            "Purpose of the NDA",
            "Effective date (YYYY-MM-DD)",
            "How long the MNDA lasts (fixed N years, or perpetual)",
            "How long information stays confidential (fixed N years, or perpetual)",
            "Governing law (US state, e.g. 'Delaware')",
            "Jurisdiction for disputes (city/county and state, e.g. 'New Castle, Delaware')",
        ],
    },

    "Mutual-NDA-coverpage": {
        "name": "Mutual NDA Cover Page",
        "description": "Common Paper Mutual NDA cover page with fill-in fields for parties and key terms",
        "filename": "Mutual-NDA-coverpage.md",
        "default_values": {
            "purpose": "Evaluating whether to enter into a business relationship with the other party.",
            "effectiveDate": "",
            "mndaTermType": "fixed",
            "mndaTermYears": "1",
            "confidentialityTermType": "fixed",
            "confidentialityTermYears": "1",
            "governingLaw": "",
            "jurisdiction": "",
            "party1Name": "",
            "party1Title": "",
            "party1Company": "",
            "party1Address": "",
            "party2Name": "",
            "party2Title": "",
            "party2Company": "",
            "party2Address": "",
        },
        "questions_order": [
            "Party 1: name and company (one question)",
            "Party 1: job title and mailing address (one question)",
            "Party 2: name and company (one question)",
            "Party 2: job title and mailing address (one question)",
            "Purpose of the NDA",
            "Effective date (YYYY-MM-DD)",
            "How long the MNDA lasts (fixed N years, or perpetual)",
            "How long information stays confidential (fixed N years, or perpetual)",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "CSA": {
        "name": "Cloud Service Agreement",
        "description": "Common Paper standard Cloud Service Agreement",
        "filename": "CSA.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerTitle": "",
            "customerCompany": "",
            "customerAddress": "",
            "subscriptionPeriod": "",
            "technicalSupport": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the company offering the cloud service): name and company",
            "Provider: job title and mailing address",
            "Customer: name and company",
            "Customer: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Subscription period (e.g. '1 year from effective date')",
            "Technical support description (e.g. 'Email support during business hours')",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "design-partner-agreement": {
        "name": "Design Partner Agreement",
        "description": "Common Paper standard Design Partner Agreement",
        "filename": "design-partner-agreement.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "partnerName": "",
            "partnerTitle": "",
            "partnerCompany": "",
            "partnerAddress": "",
            "term": "",
            "fees": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the company offering the product): name and company",
            "Provider: job title and mailing address",
            "Design Partner: name and company",
            "Design Partner: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Agreement term (e.g. '1 year')",
            "Fees (e.g. 'No fees — access provided at no charge' or specific amount)",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "sla": {
        "name": "Service Level Agreement",
        "description": "Common Paper Service Level Agreement",
        "filename": "sla.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerCompany": "",
            "customerAddress": "",
            "targetUptime": "",
            "targetResponseTime": "",
            "supportChannel": "",
            "uptimeCredit": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the company providing the service): name and company",
            "Customer: name and company",
            "Effective date (YYYY-MM-DD)",
            "Target uptime percentage (e.g. '99.9%')",
            "Target response time for support requests (e.g. '4 business hours')",
            "Support channel (e.g. 'Email at support@provider.com')",
            "Uptime credit remedy (e.g. '10% of monthly fees for each 1% below target')",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "psa": {
        "name": "Professional Services Agreement",
        "description": "Common Paper standard Professional Services Agreement",
        "filename": "psa.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerTitle": "",
            "customerCompany": "",
            "customerAddress": "",
            "servicesDescription": "",
            "deliverables": "",
            "rejectionPeriod": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the company providing professional services): name and company",
            "Provider: job title and mailing address",
            "Customer: name and company",
            "Customer: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Description of services to be provided",
            "Deliverables (what will be delivered)",
            "Rejection period for deliverables (e.g. '10 business days')",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "DPA": {
        "name": "Data Processing Agreement",
        "description": "Common Paper Data Processing Agreement",
        "filename": "DPA.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerCompany": "",
            "customerAddress": "",
            "categoriesOfPersonalData": "",
            "categoriesOfDataSubjects": "",
            "specialCategoryData": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the data processor): name and company",
            "Customer (the data controller): name and company",
            "Effective date (YYYY-MM-DD)",
            "Categories of personal data to be processed (e.g. 'Names, email addresses, usage logs')",
            "Categories of data subjects (e.g. 'Customers of the Controller')",
            "Special category data (e.g. 'None' or describe any sensitive data)",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "Partnership-Agreement": {
        "name": "Partnership Agreement",
        "description": "Common Paper standard Partnership Agreement",
        "filename": "Partnership-Agreement.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "partnerName": "",
            "partnerTitle": "",
            "partnerCompany": "",
            "partnerAddress": "",
            "obligations": "",
            "territory": "",
            "paymentProcess": "",
            "paymentSchedule": "",
            "endDate": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Your company (Provider): name and company",
            "Provider: job title and mailing address",
            "Partner: name and company",
            "Partner: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Partner obligations under this agreement",
            "Territory for trademark license (e.g. 'Worldwide' or specific region)",
            "Payment process (e.g. 'Wire transfer within 30 days of invoice')",
            "Payment schedule (e.g. 'Monthly' or 'Quarterly')",
            "End date of the agreement (YYYY-MM-DD)",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "Software-License-Agreement": {
        "name": "Software License Agreement",
        "description": "Common Paper standard Software License Agreement",
        "filename": "Software-License-Agreement.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerTitle": "",
            "customerCompany": "",
            "customerAddress": "",
            "subscriptionPeriod": "",
            "permittedUses": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the software licensor): name and company",
            "Provider: job title and mailing address",
            "Customer (the licensee): name and company",
            "Customer: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Subscription/license period (e.g. '1 year from effective date')",
            "Permitted uses of the software",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "Pilot-Agreement": {
        "name": "Pilot Agreement",
        "description": "Common Paper standard Pilot Agreement",
        "filename": "Pilot-Agreement.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerTitle": "",
            "customerCompany": "",
            "customerAddress": "",
            "pilotPeriod": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the company offering the pilot): name and company",
            "Provider: job title and mailing address",
            "Customer: name and company",
            "Customer: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Pilot period duration (e.g. '90 days from effective date')",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "BAA": {
        "name": "Business Associate Agreement",
        "description": "Common Paper standard Business Associate Agreement",
        "filename": "BAA.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "companyName": "",
            "companyTitle": "",
            "companyCompany": "",
            "companyAddress": "",
            "limitations": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Business Associate (Provider): name and company",
            "Provider: job title and mailing address",
            "Covered Entity (Company): name and company",
            "Company: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Limitations on use of PHI (Protected Health Information)",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },

    "AI-Addendum": {
        "name": "AI Addendum",
        "description": "Common Paper Standard AI Addendum for AI-related services",
        "filename": "AI-Addendum.md",
        "default_values": {
            "effectiveDate": "",
            "providerName": "",
            "providerTitle": "",
            "providerCompany": "",
            "providerAddress": "",
            "customerName": "",
            "customerTitle": "",
            "customerCompany": "",
            "customerAddress": "",
            "trainingRestrictions": "",
            "improvementRestrictions": "",
            "governingLaw": "",
            "jurisdiction": "",
        },
        "questions_order": [
            "Provider (the AI service provider): name and company",
            "Provider: job title and mailing address",
            "Customer: name and company",
            "Customer: job title and mailing address",
            "Effective date (YYYY-MM-DD)",
            "Training restrictions (can the provider use customer data to train AI models? e.g. 'No' or specify conditions)",
            "Improvement restrictions (can the provider use customer data for model improvement? e.g. 'No' or specify conditions)",
            "Governing law (US state)",
            "Jurisdiction for disputes (city/county and state)",
        ],
    },
}


def get_doc_type(key: str) -> dict[str, Any]:
    """Return doc type config or raise KeyError."""
    if key not in DOC_TYPES:
        raise KeyError(f"Unknown document type: {key!r}")
    return DOC_TYPES[key]


def default_values_for(key: str) -> dict:
    return dict(get_doc_type(key)["default_values"])
